yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/comment/",
         views.add_comment, name="add_comment"),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
"""yatube URL Configuration."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls)
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:index" %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="YaLogo">
      <span style="color:red">Ya</span>tube</a>
    </a>

    {% with request.resolver_match.view_name as view_name %}

    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:author" %}active{% endif %}" 
        href="{% url "about:author" %}">About</a>
      </li>

      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:tech" %}active{% endif %}" 
        href="{% url "about:tech" %}">Tech</a>
      </li>

      {% if user.is_authenticated %}

      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == "posts:post_create" %}active{% endif %}" 
        href="{% url "posts:post_create" %}">New Post</a>
      </li>

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "password_change" %}active{% endif %}" 
        href="{% url "password_change" %}">Change Password</a>
      </li>

      <li class="nav-item">
        <a class="nav-link link-light" href="{% url "logout" %}">Log Out</a>
      </li>

      <li>
        User: {{ user.username }}
      <li>

      {% else %}

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "login" %}active{% endif %}" 
        href="{% url "login" %}">Log In</a>
      </li>

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "users:signup" %}active{% endif %}" 
        href="{% url "users:signup" %}">Sign Up</a>
      </li>
      
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>