yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/comment/",
         views.add_comment, name="add_comment"),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
"""yatube URL Configuration."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls)
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from core.models import ModelWithDateAndText
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()

CHARS_OF_POST_TEXT = 15
CHARS_OF_COMMENT_TEXT = 15


class Group(models.Model):
    title = models.CharField("Group title", max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(ModelWithDateAndText):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Author"
    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Group",
        help_text="Choose group",
    )

    image = models.ImageField(
        "Image",
        upload_to="posts/",
        blank=True
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.text[:CHARS_OF_POST_TEXT]


class Comment(ModelWithDateAndText):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Post",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Author",
    )

    def __str__(self):
        return self.text[:CHARS_OF_COMMENT_TEXT]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Follower",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Author",
    )

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=["user", "author"],
                name="follow_must_be_unique",
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text", )

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post

User = get_user_model()

POSTS_PER_PAGE = 10


def index(request):
    template = "posts/index.html"
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "group": group,
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author__username=username)
    posts_count = posts.count()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "posts_count": posts_count,
        "author": author,
    }
    if request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists():
        context["following"] = True
        return render(request, template, context)

    return render(request, template, context)


def post_detail(request, post_id):
    template = "posts/post_detail.html"
    post = get_object_or_404(Post, id=post_id)
    posts_count = Post.objects.filter(author=post.author).count()
    comments = Comment.objects.filter(post_id=post_id)
    context = {
        "posts_count": posts_count,
        "post": post,
        "form": CommentForm(),
        "comments": comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = "posts/create_post.html"
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=request.user)

    return render(request, template, {"form": form})


@login_required
def post_edit(request, post_id):
    template = "posts/create_post.html"
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post,
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:post_detail", post_id=post_id)

        return render(request, template,
                      {"post": post,
                       "form": form,
                       "is_edit": True})

    return redirect("posts:post_detail", post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    template = "posts/follow.html"
    following = Follow.objects.filter(
        user=request.user
    ).values_list("author_id", flat=True)
    posts = Post.objects.filter(author_id__in=following)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "posts": posts,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    already_followed = Follow.objects.filter(
        user=request.user, author=author).count()
    if request.user != author and already_followed == 0:
        Follow.objects.create(user=request.user, author=author)
        return redirect("posts:follow_index")

    return redirect("posts:index")


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:follow_index")

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  {% if is_edit %} 
    Edit Post 
  {% else %} 
    Create Post 
  {% endif %}
{% endblock %}
  {% block content %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Edit Post 
            {% else %} 
              Create Post 
            {% endif %}    
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" enctype="multipart/form-data" action="{% url "posts:post_edit" post.id %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url "posts:post_create" %}">
            {% endif %}
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>    
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Save
                  {% else %}
                    Add
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Followings {% endblock %}
{% block content %}
  {% include "posts/includes/switcher.html" %}
    {% for post in page_obj %}
      {% include "posts/includes/post_list.html" %}
        {% if post.group %}
          <a href="{% url "posts:group_list" post.group.slug %}"> All posts by Group: {{ post.group }}</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group }} {% endblock %}
{% block content %}
  <h1> {{ group }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    {% include "posts/includes/post_list.html" %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% block title %} Latest Updates {% endblock %}
{% block content %}
  {% cache 20 index_page %}
  {% include "posts/includes/switcher.html" %}
    {% for post in page_obj %}
      {% include "posts/includes/post_list.html" %}
        {% if post.group %}
          <a href="{% url "posts:group_list" post.group.slug %}"> All posts by Group: {{ post.group }}</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include "posts/includes/paginator.html" %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %} Пост «{{ post.text|truncatechars:30 }}» {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Publiction date: {{ post.created|date:"d E Y" }} 
        </li>  
        {% if post.group %}
          <li class="list-group-item">
            Group: {{ post.group }}
            <p>
              {% if post.group %}
                <a href="{% url "posts:group_list" post.group.slug %}"> All posts by Group: {{ post.group }}</a>
              {% endif %}
            </p>
          </li>  
        {% endif %}    
          <li class="list-group-item">
            Author: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Author's posts count: <span>{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url "posts:profile" post.author.username %}">
            All posts by {{ post.author.get_full_name }}
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{ post.text }} </p>

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url "posts:profile" comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
              <p>
                {{ comment.text }}
                <p> 
                  {{ comment.created }}
                </p>  
              </p>
            </div>
          </div>
      {% endfor %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Post Comment:</h5>
          <div class="card-body">
            <form method="post" action="{% url "posts:add_comment" post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      {% endif %} 

      {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">
          Edit Post
        </a>
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} User profile {{ author.username }} {% endblock %}
{% block content %}
  <div class="mb-5">
  <h1> All posts by {{ author.get_full_name }} ({{ author.username }}) </h1>
  <h3> Total posts: {{ posts_count }} </h3>
  {% if request.user == author %}
  {% else %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url "posts:profile_unfollow" author.username %}" role="button"
      >
        Unfollow
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url "posts:profile_follow" author.username %}" role="button"
      >
        Follow
      </a>
    {% endif %}
  {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
        <li>
          Publication date: {{ post.created|date:"d E Y" }}
        </li>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}  
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}"> All posts by Group: {{ post.group }}</a>
      {% endif %}
      <p><a href="{% url "posts:post_detail" post.id %}"> Post Details </a></p>
    </article>       
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}  
{% endblock %}